# Docs:
# https://golangci-lint.run/usage/linters/

linters:
  enable-all: true
  disable:
    - containedctx
    - contextcheck
    - cyclop
    - exhaustivestruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - goerr113 
    - gomnd
    - ifshort
    - interfacer
    - ireturn
    - lll
    - nestif
    - nilnil
    - nlreturn
    - noctx
    - revive
    - tagliatelle
    - testpackage
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl

linters-settings:
  gci:
    # put imports beginning with prefix after 3rd-party packages;
    # only support one prefix
    # if not set, use goimports.local-prefixes
    local-prefixes: github.com/safing
  godox:
    # report any comments starting with keywords, this is useful for TODO or FIXME comments that
    # might be left in the code accidentally and should be resolved before merging
    keywords:
      - FIXME
