name: Go
on:
  push:
    branches:
      - feature/actions/*
      - fix/actions/*
  pull_request:
    branches:
      - master
      - develop
jobs:
  test:
    name: Testing ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -d -u github.com/golang/dep
          go install github.com/golang/dep/cmd/dep
          $GOPATH/bin/dep ensure

      - name: Run tests
        run: ./test --scripted
